/** 감사대사 public API */
function api_uploadBankTransactions(request) { return apiHandler_({ operation: 'uploadBankTransactions', input: request, requireLogin: true, access: accountingApiAccess_('edit'), service: function (input, context) { return uploadBankTransactions_(input || {}, context); } }); }
function api_runReconciliation(request) { return apiHandler_({ operation: 'runReconciliation', input: request, requireLogin: true, access: accountingApiAccess_('approve'), service: function (input, context) { return runReconciliation_(input || {}, context); } }); }
function api_getReconciliationList(filter) { return apiHandler_({ operation: 'getReconciliationList', input: filter, requireLogin: true, access: accountingApiAccess_('view'), service: function (input) { return getReconciliationList_(input || {}); } }); }
function api_getReconciliationDetail(reconciliationId) { return apiHandler_({ operation: 'getReconciliationDetail', input: reconciliationId, requireLogin: true, access: accountingApiAccess_('view'), service: function (id) { return getReconciliationDetail_(id); } }); }
function api_getReconciliationCandidates(request) { return apiHandler_({ operation: 'getReconciliationCandidates', input: request, requireLogin: true, access: accountingApiAccess_('view'), service: function (input) { return getReconciliationCandidates_(input || {}); } }); }
function api_linkReconciliation(request) { return apiHandler_({ operation: 'linkReconciliation', input: request, requireLogin: true, access: accountingApiAccess_('approve'), service: function (input, context) { return linkReconciliation_(input || {}, context); } }); }
function api_createLedgerFromReconciliation(request) { return apiHandler_({ operation: 'createLedgerFromReconciliation', input: request, requireLogin: true, access: accountingApiAccess_('approve'), service: function (input, context) { return createLedgerFromReconciliation_(input || {}, context); } }); }
function api_getBankOcrLogs(request) { return apiHandler_({ operation: 'getBankOcrLogs', input: request, requireLogin: true, access: accountingApiAccess_('view'), service: function (input) { return getBankOcrLogs_(input || {}); } }); }
